name: freezd
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.1.0
  freezed_annotation:


dev_dependencies:
  build_runner:
  freezed: ^0.12.2
  json_serializable: ^3.5.0

flutter:
  uses-material-design: true
